### PR TITLE
enable weth in goerli

### PR DESCRIPTION
**Pull request by fritzschoff**
Screenshot 2023-05-29 at 18 23 18

### CODE REVIEW

**Review by dbeal-eth — CHANGES_REQUESTED** [review]
1. Mainnet ci check is failing
2. I would rather not have a setting for a boolean just to identify if weth is enabled or not. We should find a better solution.

**Comment by dbeal-eth** [comment]
It looks like mainnet was failing before this pr. Still, not an excuse for it not working now as the error seems to be directly related to your changes. Let's get the ci all the way working.

**Comment by fritzschoff** [comment]
> 1. Mainnet ci check is failing
> 2. I would rather not have a setting for a boolean just to identify if weth is enabled or not. We should find a better solution.

boolean is fine here. Its pretty clear

**Comment by cavalier-eth** [comment]
@fritzschoff this looks old can it be closed?

**Pull request closed without merging**
